# Generated by Django 6.0.4 on 2026-04-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='quantidade',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='preco_unitario',
            new_name='preco',
        ),
        migrations.AddField(
            model_name='venda',
            name='canal',
            field=models.CharField(default='Online', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='receita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='sku',
            field=models.CharField(default='SKU000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='vendas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.CharField(max_length=150),
        ),
    ]
