# Generated by Django 6.0.4 on 2026-06-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_quantidade_venda_estoque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('abertura', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fechamento', models.DecimalField(decimal_places=4, max_digits=10)),
                ('maxima', models.DecimalField(decimal_places=4, max_digits=10)),
                ('minima', models.DecimalField(decimal_places=4, max_digits=10)),
                ('variacao_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotação do Dólar',
                'verbose_name_plural': 'Cotações do Dólar',
                'ordering': ['-data'],
            },
        ),
    ]
